-- =====================================================================
-- Access control for /ext-api — roles, permissions, menus, IN `attendance`
--
-- Design: docs/access_control.md. Read §7 (Preconditions) before turning any
-- of this on; in particular `WOW_ACCEPT_DU_TOKEN` must be false, or a forged
-- token can claim any identity and every check here is decoration.
--
-- WHAT THIS FILE DOES
--   1. Creates this service's OWN copy of the six RBAC tables, in the
--      `attendance` schema — the same move sql/005 made for the ext-api gate.
--   2. Copies the rows `ictcell` holds today, ids preserved, as the starting
--      point. Guarded, so a re-run copies nothing twice.
--   3. Adds the endpoint→permission map and the two decision functions, which
--      read `attendance` only. Nothing in this schema references `ictcell`.
--
-- APPLYING THIS FILE CHANGES NO BEHAVIOUR. Every endpoint rule is seeded with
-- `enforce = false`, and the service does not read these objects yet (the
-- middleware change is docs/access_control.md §6). Flipping `enforce` is what
-- starts refusing, one endpoint at a time.
--
-- THE COST OF OWNING A COPY — know this before applying
--   The ERP's admin screens (`/access-roles`, `/role_list`) write
--   `ictcell.*`. From the moment this service reads `attendance.*`, a role
--   assigned in those screens DOES NOT REACH IT. Three ways to resolve that,
--   and one of them has to be chosen — see §9 for the statements:
--     a. Point the ERP's admin screens at `attendance.*` (same database, a
--        schema name in their queries). One source of truth again, this
--        service owns it. RECOMMENDED.
--     b. Re-sync on a schedule with §9's statement. Simple, and stale between
--        runs — a revoked role keeps working until the next sync.
--     c. Administer roles here instead, which needs admin endpoints this
--        service does not have.
--   Until one is chosen, treat `attendance.app_users.role_id` as the thing to
--   edit by hand, and expect the ERP screens to disagree with reality.
--
-- IDENTITY COMES FROM `app_users.person_id`, which is the bearer token's `sub`
-- — the 10-digit employee id for staff, the DU user_id for students (see
-- src/routes/auth.rs). UNIQUE, which makes the token→role join one lookup.
--
-- PII: `app_users` carries usernames (DU email addresses) for every account.
-- The copy is inside the same database, readable by the same role, so this
-- adds no new exposure — but it is a second place that data now lives, and it
-- is one more thing to drop if the access-control work is abandoned (§9).
--
-- THE `ictcell` ORIGINALS ARE NOT DROPPED. duerp-api still reads them, and
-- this file must not break the ERP. Leave them alone.
--
-- Idempotent: CREATE ... IF NOT EXISTS / CREATE OR REPLACE / guarded INSERT
-- throughout. Re-running changes nothing — including `enforce` flags, which
-- are set on INSERT only, so a re-run never re-opens an endpoint you closed.
--
--     psql "$DATABASE_URL" -f sql/006_access_control.sql
--     cargo test --test access_control_sql
--
-- TO ROLL BACK COMPLETELY (nothing else references these):
--     DROP FUNCTION IF EXISTS attendance.access_profile(bigint, text);
--     DROP FUNCTION IF EXISTS attendance.ext_api_can_call(bigint, varchar);
--     DROP TABLE IF EXISTS attendance.ext_api_endpoint_permissions,
--                          attendance.user_permission_overrides,
--                          attendance.role_permissions,
--                          attendance.menu_items,
--                          attendance.app_users,
--                          attendance.resources,
--                          attendance.roles CASCADE;
-- =====================================================================

CREATE SCHEMA IF NOT EXISTS attendance;

-- ---------------------------------------------------------------------
-- 1 · The RBAC tables, in `attendance`
--
-- Column-for-column what `ictcell` holds, so the rows copy across unchanged
-- and anyone who knows the ERP's model already knows this one. Every foreign
-- key points INSIDE `attendance`: a cross-schema FK would leave this service's
-- access model breaking whenever duerp-api deleted a row, which is exactly the
-- coupling this move exists to remove.
--
-- One addition, and it is the reason the move is convenient rather than
-- merely defensible: `menu_items.platforms`, which needed another team's
-- agreement while the table was theirs (docs/access_control.md §13) and is
-- simply a column here.
-- ---------------------------------------------------------------------

-- A named role: 'admin', 'faculty', 'card_desk'. `is_system` marks the ones
-- the ERP ships and nobody should rename.
CREATE TABLE IF NOT EXISTS attendance.roles (
    id         integer     PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    key        text        NOT NULL UNIQUE,
    name       text        NOT NULL,
    is_system  boolean     NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE attendance.roles IS
    'Named roles. Copied from ictcell.roles; this service reads THIS copy. See docs/access_control.md.';

-- The permission vocabulary. One key gates a desktop menu item, a mobile tab
-- and the endpoints behind them, so a role change moves all three together.
CREATE TABLE IF NOT EXISTS attendance.resources (
    id         integer     PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    key        text        NOT NULL UNIQUE,
    name       text        NOT NULL,
    category   text,
    created_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE attendance.resources IS
    'Permission keys ("nfc.card.register"). The shared vocabulary for menus, features and endpoint rules.';

-- Which permissions a role holds.
CREATE TABLE IF NOT EXISTS attendance.role_permissions (
    role_id     integer NOT NULL REFERENCES attendance.roles(id)     ON DELETE CASCADE,
    resource_id integer NOT NULL REFERENCES attendance.resources(id) ON DELETE CASCADE,
    PRIMARY KEY (role_id, resource_id)
);

-- One row per person who can sign in. `person_id` is the token's `sub`.
--
-- `du_base_role` is DU's own free-text role string, kept because it is what
-- the accounts currently carry and the only clue for a backfill; `role_id` is
-- the one this service decides with. See docs/access_control.md §7.4 — today
-- `role_id` is NULL for every copied row, which means everybody is denied
-- until somebody fills it in.
CREATE TABLE IF NOT EXISTS attendance.app_users (
    id            integer     PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    person_id     bigint      NOT NULL UNIQUE,
    username      text,
    du_base_role  text,
    role_id       integer     REFERENCES attendance.roles(id),
    -- Anything other than 'active' refuses every gated call immediately,
    -- whatever the person's token says. Tokens live ~730 hours with no
    -- revocation list, so this is the kill switch.
    status        text        NOT NULL DEFAULT 'active',
    last_login_at timestamptz,
    created_at    timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE attendance.app_users IS
    'Sign-in accounts. person_id = the bearer token''s `sub`. Copied from ictcell.app_users; carries DU email addresses.';

-- Per-person exceptions to the role. This is "allow one specific person" and
-- "everyone in this role except her", and the PK means a person has at most
-- one verdict per permission.
CREATE TABLE IF NOT EXISTS attendance.user_permission_overrides (
    user_id     integer NOT NULL REFERENCES attendance.app_users(id) ON DELETE CASCADE,
    resource_id integer NOT NULL REFERENCES attendance.resources(id) ON DELETE CASCADE,
    effect      text    NOT NULL CHECK (effect IN ('grant', 'deny')),
    PRIMARY KEY (user_id, resource_id)
);

-- The navigation tree each client renders, gated by `resource_id` and scoped
-- by `platforms`. A row with no `resource_id` is a container: it carries no
-- permission of its own and appears only if something under it survived.
CREATE TABLE IF NOT EXISTS attendance.menu_items (
    id          integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    parent_id   integer REFERENCES attendance.menu_items(id) ON DELETE CASCADE,
    label       text    NOT NULL,
    icon        text,
    route       text,
    resource_id integer REFERENCES attendance.resources(id),
    sort_order  integer NOT NULL DEFAULT 0,
    is_active   boolean NOT NULL DEFAULT true,
    -- DEFAULT '{desktop}' is what keeps a copied ERP menu behaving exactly as
    -- it does today: a mobile client gets only rows somebody deliberately
    -- marked for it, never a desktop tree squeezed onto a phone.
    platforms   text[]  NOT NULL DEFAULT '{desktop}'
);

COMMENT ON COLUMN attendance.menu_items.platforms IS
    'Which clients render this item: desktop | mobile | kiosk. Read by attendance.access_profile().';

-- ---------------------------------------------------------------------
-- 2 · Copy what `ictcell` holds today
--
-- IDS ARE PRESERVED. `user_permission_overrides` references `app_users.id` and
-- `menu_items.parent_id` references its own table, so renumbering would
-- silently re-point overrides at the wrong people. Identity columns accept an
-- explicit id (GENERATED BY DEFAULT, not ALWAYS) precisely so this works, and
-- §3 moves the sequences past the copied values.
--
-- Insert order is FK order: resources and roles, then the tables that point at
-- them, then menu_items (self-referencing — parents before children, which
-- `ORDER BY id` gives since a parent is always created first).
--
-- `ON CONFLICT DO NOTHING` with no target, so an id OR a key collision is
-- skipped rather than aborting the file. A re-run therefore copies nothing,
-- and — importantly — a row edited HERE is never overwritten by the ERP's
-- version on a later re-run.
--
-- This is a SNAPSHOT, not a sync. See the header, and §9 for the re-sync.
-- ---------------------------------------------------------------------

INSERT INTO attendance.resources (id, key, name, category, created_at)
SELECT id, key, name, category, created_at FROM ictcell.resources
ON CONFLICT DO NOTHING;

INSERT INTO attendance.roles (id, key, name, is_system, created_at)
SELECT id, key, name, is_system, created_at FROM ictcell.roles
ON CONFLICT DO NOTHING;

INSERT INTO attendance.role_permissions (role_id, resource_id)
SELECT role_id, resource_id FROM ictcell.role_permissions
ON CONFLICT DO NOTHING;

INSERT INTO attendance.app_users (id, person_id, username, du_base_role, role_id, status, last_login_at, created_at)
SELECT id, person_id, username, du_base_role, role_id, status, last_login_at, created_at
  FROM ictcell.app_users
ON CONFLICT DO NOTHING;

INSERT INTO attendance.user_permission_overrides (user_id, resource_id, effect)
SELECT user_id, resource_id, effect FROM ictcell.user_permission_overrides
ON CONFLICT DO NOTHING;

INSERT INTO attendance.menu_items (id, parent_id, label, icon, route, resource_id, sort_order, is_active, platforms)
SELECT id, parent_id, label, icon, route, resource_id, sort_order, is_active,
       -- `platforms` exists on the ictcell table only if the earlier version
       -- of this migration was applied there. Reading it through to_jsonb
       -- keeps this file working either way: a missing key yields no rows,
       -- array_agg gives NULL, and the COALESCE lands on desktop.
       coalesce(
           (SELECT array_agg(x) FROM jsonb_array_elements_text(to_jsonb(m) -> 'platforms') AS x),
           '{desktop}')
  FROM ictcell.menu_items m
 ORDER BY id
ON CONFLICT DO NOTHING;

-- ---------------------------------------------------------------------
-- 3 · Move the sequences past the copied ids
--
-- Without this the next INSERT starts at 1 and collides with a copied row.
-- `is_called = true` (the third argument) so the NEXT value is max(id) + 1
-- rather than max(id) itself. COALESCE covers an empty table.
-- ---------------------------------------------------------------------

SELECT setval(pg_get_serial_sequence('attendance.roles', 'id'),
              COALESCE((SELECT max(id) FROM attendance.roles), 1), true);
SELECT setval(pg_get_serial_sequence('attendance.resources', 'id'),
              COALESCE((SELECT max(id) FROM attendance.resources), 1), true);
SELECT setval(pg_get_serial_sequence('attendance.app_users', 'id'),
              COALESCE((SELECT max(id) FROM attendance.app_users), 1), true);
SELECT setval(pg_get_serial_sequence('attendance.menu_items', 'id'),
              COALESCE((SELECT max(id) FROM attendance.menu_items), 1), true);

-- ---------------------------------------------------------------------
-- 4 · This service's permission keys
--
-- Added after the copy so they survive on a database where `ictcell` never
-- had them. Prefixed by subsystem (`nfc.`, `face.`) so it is obvious which
-- system a key belongs to.
--
-- `attendance.report.view`, `attendance.settings` and `admin.logs.view` come
-- across in the copy with their role grants attached — reused below rather
-- than duplicated under a new name.
--
-- `nfc.card.reassign` gates a FIELD, not a path: `force_reassign` on
-- save_card_info, which takes a card off another student. The endpoint map in
-- §7 cannot express it; the handler checks it (docs §5).
-- ---------------------------------------------------------------------

INSERT INTO attendance.resources (key, name, category) VALUES
    ('nfc.card.read',     'NFC · Read card info',          'Attendance Devices'),
    ('nfc.card.status',   'NFC · Check registration',      'Attendance Devices'),
    ('nfc.card.register', 'NFC · Register / update card',  'Attendance Devices'),
    ('nfc.card.reassign', 'NFC · Reassign an issued card', 'Attendance Devices'),
    ('face.enroll',       'Face · Enroll',                 'Attendance Devices'),
    ('face.verify',       'Face · Verify / check-in',      'Attendance Devices')
ON CONFLICT (key) DO NOTHING;

-- ---------------------------------------------------------------------
-- 4b · Which roles hold this service's permissions
--
-- The copied roles arrived with the ERP's own grants and know nothing about
-- NFC cards or face attendance. Without this section EVERY role holds zero of
-- the six keys above — so an "admin" can manage roles and menus while being
-- refused by every endpoint in this service the moment enforcement starts.
--
-- `admin` and `superadmin` get all of them. That is the FLOOR, not the target:
-- a card desk should hold `nfc.card.register` and NOT `nfc.card.reassign`, a
-- turnstile only `nfc.card.read`. Those narrower roles do not exist yet —
-- docs/access_control.md §5 has the intended map — and creating them is a
-- decision about people, not something a migration should invent.
--
-- `admin.logs.view` is included for `admin` too. The step logs are how this
-- service is debugged, and an admin who cannot read them has to ask a DBA; the
-- ERP's copy had it on `superadmin` alone.
--
-- The two management screens an admin needs — `/access-roles` (roles and their
-- permissions) and `/role_list` (who holds which role) — are already covered:
-- `admin.roles.manage` and `admin.users.manage` came across with the copy, and
-- `attendance.access_profile` puts their menu rows in the payload for anyone
-- holding them. What was missing was somebody actually being an admin; see
-- section 10.
-- ---------------------------------------------------------------------

INSERT INTO attendance.role_permissions (role_id, resource_id)
SELECT r.id, res.id
  FROM attendance.roles r, attendance.resources res
 WHERE r.key IN ('admin', 'superadmin')
   AND res.key IN ('nfc.card.read', 'nfc.card.status', 'nfc.card.register',
                   'nfc.card.reassign', 'face.enroll', 'face.verify',
                   'admin.logs.view')
ON CONFLICT DO NOTHING;

-- ---------------------------------------------------------------------
-- 4c · Roles for the people and devices that use THIS service
--
-- `admin` above can do everything, which is right for administrators and wrong
-- for everyone else. These three are the working roles from
-- docs/access_control.md §5, and the point of them is what they do NOT hold.
--
-- `card_desk` — a clerk issuing cards. Registers a card, checks whether a
--   student already has one, reads a card that was handed in. **Not**
--   `nfc.card.reassign`: taking a card off another student is the one
--   irreversible thing here, and it is checked separately inside
--   save_card_info (section 8). One clerk in a hundred needs it; that one gets
--   a per-person `grant` override, not a wider role.
--
-- `reader` — an unattended device at a door. Reads a card, verifies a face,
--   and nothing else: no registration, no enrolment, no reports, no logs. A
--   device account's credentials live in a machine on a corridor, so its role
--   is the one worth keeping narrowest.
--
-- `enrollment_desk` — registers a student's face, and answers "is this person
--   enrolled?" (`check`) and "who is" (`enrolled`), which are the same
--   permission because they are the same job. **Not** `face.verify`: marking
--   somebody present is the door's function, not the desk's, and a desk that
--   wants to confirm an enrolment worked asks `check` instead. Nor
--   `attendance.report.view` — enrolling people is not a reason to read their
--   attendance history.
--
-- Both carry `dashboard.view`, as every ERP role does, so a human signing in
-- with one lands on a page rather than a bare shell.
--
-- `is_system = false`, unlike the roles copied from the ERP: these are this
-- deployment's own, and the Access Roles screen may edit them freely.
--
-- NOBODY IS IN EITHER ROLE YET. Creating a role is a migration; deciding which
-- people and which devices hold it is not — see section 10, and
-- docs/access_control.md §10 for why a device needs an account at all.
--
-- IF THESE ROLES ALREADY EXIST they are left exactly as they are, grants
-- included. A re-run of this file must never widen a role somebody narrowed.
-- ---------------------------------------------------------------------

INSERT INTO attendance.roles (key, name, is_system) VALUES
    ('card_desk',       'Card Desk',       false),
    ('reader',          'Card Reader',     false),
    ('enrollment_desk', 'Enrollment Desk', false)
ON CONFLICT (key) DO NOTHING;

INSERT INTO attendance.role_permissions (role_id, resource_id)
SELECT r.id, res.id
  FROM (VALUES
    -- Issue and look up cards, but never take one away.
    ('card_desk', 'nfc.card.register'),
    ('card_desk', 'nfc.card.status'),
    ('card_desk', 'nfc.card.read'),
    ('card_desk', 'dashboard.view'),
    -- The door: tap a card, verify a face.
    ('reader',    'nfc.card.read'),
    ('reader',    'face.verify'),
    ('reader',    'dashboard.view'),
    -- Register faces, and see who is registered.
    ('enrollment_desk', 'face.enroll'),
    ('enrollment_desk', 'dashboard.view')
  ) AS want(role_key, resource_key)
  JOIN attendance.roles     r   ON r.key   = want.role_key
  JOIN attendance.resources res ON res.key = want.resource_key
ON CONFLICT DO NOTHING;

-- ---------------------------------------------------------------------
-- 5 · Endpoint → permission map
--
-- The missing link: `resources` holds permission keys, `ext_api_allowed_ips`
-- holds paths, and until now nothing said which permission a path requires.
--
-- Matched on the FULL path, exactly, like `ext_api_allowed_ips` — not a
-- prefix. A new endpoint is unreachable until someone says who may reach it.
-- ---------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS attendance.ext_api_endpoint_permissions (
    id            bigserial    PRIMARY KEY,
    -- e.g. '/ext-api/nfc-card/save_card_info'
    endpoint      varchar(255) NOT NULL,
    -- NULL = "any authenticated caller": today's behaviour, written down, for
    -- the paths that genuinely need no role (the access profile reports only
    -- the caller's own access; a turnstile may be deliberately open).
    resource_key  text,
    -- false = AUDIT MODE. The verdict is computed and logged; the request is
    -- served anyway. This is how the rollout happens without locking anyone
    -- out (docs §8), and how a mistake is undone with one UPDATE and no
    -- redeploy.
    enforce       boolean      NOT NULL DEFAULT false,
    is_active     boolean      NOT NULL DEFAULT true,
    -- Why this row is the way it is — especially why a resource_key is NULL,
    -- which the next reader will otherwise take for an oversight.
    note          text,
    created_at    timestamptz  NOT NULL DEFAULT now(),
    updated_at    timestamptz  NOT NULL DEFAULT now(),

    CONSTRAINT ext_api_endpoint_permissions_endpoint_uq UNIQUE (endpoint)
);

COMMENT ON TABLE attendance.ext_api_endpoint_permissions IS
    'Which attendance.resources key each /ext-api path requires. enforce=false means audit-only. No row = denied, once the middleware asks.';

CREATE INDEX IF NOT EXISTS ext_api_endpoint_permissions_active_idx
    ON attendance.ext_api_endpoint_permissions (endpoint)
    WHERE is_active;

-- ---------------------------------------------------------------------
-- 5b · The audit trail the rollout is read from
--
-- `ExtAuthMiddleware` writes one row here for every request it WOULD have
-- refused — in audit mode that is most of them, which is the point: this table
-- is how "who breaks if I enforce this endpoint?" becomes a query instead of a
-- log trawl (docs/access_control.md §8).
--
-- FOLDED, NOT APPENDED. One row per (person, endpoint, reason), with a counter,
-- because during the audit phase every single tap is a denial — nobody has a
-- role yet — and a row each would be a write per request for a report nobody
-- reads line by line. The unique index is `NULLS NOT DISTINCT` so the
-- no-token case (person_id IS NULL) folds into one row too, rather than one
-- per request.
--
-- The write is detached in the handler path: a failed INSERT here must never
-- delay or fail a request the verdict already allowed.
--
-- `token_source` is what makes docs §7.1 measurable: 'legacy' means the caller
-- arrived on a DU token whose signature CANNOT be verified, so the identity
-- this row records is unproven. Those have to reach zero before enforcement
-- means anything.
-- ---------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS attendance.ext_api_access_audit (
    id            bigserial    PRIMARY KEY,
    -- NULL = no usable bearer token on the request.
    person_id     bigint,
    endpoint      varchar(255) NOT NULL,
    -- The verdict's `reason`: no_rule, not_in_role, no_account,
    -- account_inactive, denied_by_override, unknown_resource, check_failed.
    reason        text         NOT NULL,
    -- 'ours' | 'legacy' | 'none' — see the note above.
    token_source  text,
    -- What the endpoint's rule said at the time...
    rule_enforces boolean      NOT NULL DEFAULT false,
    -- ...and whether the request was actually refused. `false` while auditing.
    refused       boolean      NOT NULL DEFAULT false,
    hits          bigint       NOT NULL DEFAULT 1,
    first_seen    timestamptz  NOT NULL DEFAULT now(),
    last_seen     timestamptz  NOT NULL DEFAULT now(),

    CONSTRAINT ext_api_access_audit_uq
        UNIQUE NULLS NOT DISTINCT (person_id, endpoint, reason)
);

COMMENT ON TABLE attendance.ext_api_access_audit IS
    'Would-be and actual access refusals, folded by (person, endpoint, reason). Written by ExtAuthMiddleware; read during the enforcement rollout.';

CREATE INDEX IF NOT EXISTS ext_api_access_audit_endpoint_idx
    ON attendance.ext_api_access_audit (endpoint, last_seen DESC);

-- ---------------------------------------------------------------------
-- 6 · The decision: may this person call this endpoint?
--
-- One function, so the rule holds for anything that asks — the middleware, a
-- psql prompt, a future admin screen. It returns a VERDICT OBJECT rather than
-- a boolean because the caller needs three things: whether to allow, whether
-- this endpoint is enforcing yet, and WHY — "nobody configured this path" and
-- "you are not in the role" send an operator to completely different places.
--
-- It FAILS CLOSED at every unknown: no rule, no account, no such resource key.
-- The one exception is an explicit `resource_key IS NULL`, which is somebody
-- writing down "open to any authenticated caller" on purpose.
-- ---------------------------------------------------------------------

CREATE OR REPLACE FUNCTION attendance.ext_api_can_call(
    p_person_id bigint,
    p_endpoint  varchar
) RETURNS jsonb
LANGUAGE plpgsql STABLE
AS $function$
DECLARE
    v_rule     RECORD;
    v_user     RECORD;
    v_resource integer;
    v_effect   text;
    v_allowed  boolean;
BEGIN
    SELECT * INTO v_rule
      FROM attendance.ext_api_endpoint_permissions
     WHERE endpoint = p_endpoint
       AND is_active;

    -- No rule, or a deactivated one. Denied — but `enforce` is reported as
    -- true so the middleware refuses rather than waving it through: an
    -- unconfigured path is exactly the case this must not be lenient about.
    IF NOT FOUND THEN
        RETURN jsonb_build_object('allowed', false, 'enforce', true,
            'reason', 'no_rule', 'endpoint', p_endpoint);
    END IF;

    IF v_rule.resource_key IS NULL THEN
        RETURN jsonb_build_object('allowed', true, 'enforce', v_rule.enforce,
            'reason', 'open_to_authenticated');
    END IF;

    SELECT id INTO v_resource FROM attendance.resources WHERE key = v_rule.resource_key;

    -- A typo'd key must never read as "allowed". It is a config error, and the
    -- reason code says so rather than blaming the caller.
    IF v_resource IS NULL THEN
        RETURN jsonb_build_object('allowed', false, 'enforce', v_rule.enforce,
            'reason', 'unknown_resource', 'resource_key', v_rule.resource_key);
    END IF;

    SELECT au.id, au.role_id, au.status, r.key AS role_key
      INTO v_user
      FROM attendance.app_users au
      LEFT JOIN attendance.roles r ON r.id = au.role_id
     WHERE au.person_id = p_person_id;

    IF NOT FOUND THEN
        RETURN jsonb_build_object('allowed', false, 'enforce', v_rule.enforce,
            'reason', 'no_account', 'person_id', p_person_id);
    END IF;

    -- The kill switch. Tokens live ~730 hours and there is no revocation list,
    -- so this is what makes "stop that person now" possible at all: the next
    -- request is refused whatever their token says.
    IF coalesce(v_user.status, '') <> 'active' THEN
        RETURN jsonb_build_object('allowed', false, 'enforce', v_rule.enforce,
            'reason', 'account_inactive', 'status', v_user.status);
    END IF;

    -- A per-person override beats the role, either way. "Everyone in this role
    -- except her" has to be expressible, and it only is if a person-level deny
    -- outranks a role-level grant. At most one row can match: the table's PK is
    -- (user_id, resource_id), so there is no grant-vs-deny tie to break here.
    SELECT effect INTO v_effect
      FROM attendance.user_permission_overrides
     WHERE user_id = v_user.id AND resource_id = v_resource;

    IF v_effect = 'deny' THEN
        RETURN jsonb_build_object('allowed', false, 'enforce', v_rule.enforce,
            'reason', 'denied_by_override');
    ELSIF v_effect = 'grant' THEN
        RETURN jsonb_build_object('allowed', true, 'enforce', v_rule.enforce,
            'reason', 'granted_by_override');
    END IF;

    v_allowed := EXISTS (
        SELECT 1 FROM attendance.role_permissions rp
         WHERE rp.role_id = v_user.role_id
           AND rp.resource_id = v_resource);

    RETURN jsonb_build_object('allowed', v_allowed, 'enforce', v_rule.enforce,
        'reason', CASE WHEN v_allowed THEN 'granted_by_role' ELSE 'not_in_role' END,
        'role', v_user.role_key,
        'resource_key', v_rule.resource_key);
END;
$function$;

COMMENT ON FUNCTION attendance.ext_api_can_call(bigint, varchar) IS
    'May this person call this path? {allowed, enforce, reason, ...}. Fails closed on no rule / no account / unknown resource.';

-- ---------------------------------------------------------------------
-- 7 · The access profile: what one person may do, and what to render
--
-- Backs `POST /ext-api/me/access` (docs §14), which both the desktop SPA and
-- the mobile app call right after login. Returns the caller's permissions, the
-- menu already filtered for their platform AND their role, and a version hash
-- the client can send back to skip a re-render.
--
-- THE MENU IS A VIEW, NOT A GATE. Hiding an item is a courtesy to the user;
-- `ext_api_can_call` above is the thing that refuses. Both read the same
-- tables so they cannot disagree — but a client that trusts this payload for
-- anything but rendering is a client with no access control at all.
--
-- The permission set here and the verdict in §6 MUST stay in step: role
-- grants, plus per-person grants, minus per-person denies. A UI that offers a
-- button the API then refuses is a bug report every single time.
-- ---------------------------------------------------------------------

CREATE OR REPLACE FUNCTION attendance.access_profile(
    p_person_id bigint,
    p_platform  text DEFAULT 'desktop'
) RETURNS jsonb
LANGUAGE plpgsql STABLE
AS $function$
DECLARE
    v_user  RECORD;
    v_perms text[];
    v_menu  jsonb;
BEGIN
    SELECT au.id, au.person_id, au.username, au.status, au.role_id,
           r.key AS role_key, r.name AS role_name
      INTO v_user
      FROM attendance.app_users au
      LEFT JOIN attendance.roles r ON r.id = au.role_id
     WHERE au.person_id = p_person_id;

    -- No account, or a suspended one: an EMPTY profile, not an error. The
    -- client renders a bare shell and every endpoint still refuses them; a
    -- failure here would only make the app look broken to someone who is
    -- merely unprivileged.
    IF NOT FOUND OR coalesce(v_user.status, '') <> 'active' THEN
        RETURN jsonb_build_object(
            'status',  'success',
            'message', 'No access profile for this user',
            'data', jsonb_build_object(
                'person_id',   p_person_id,
                'username',    NULL,
                'role',        NULL,
                'role_name',   NULL,
                'platform',    p_platform,
                'permissions', '[]'::jsonb,
                'menu',        '[]'::jsonb,
                'version',     md5('')));
    END IF;

    SELECT coalesce(array_agg(DISTINCT res.key ORDER BY res.key), '{}')
      INTO v_perms
      FROM attendance.resources res
     WHERE (EXISTS (SELECT 1 FROM attendance.role_permissions rp
                     WHERE rp.role_id = v_user.role_id
                       AND rp.resource_id = res.id)
            OR EXISTS (SELECT 1 FROM attendance.user_permission_overrides o
                        WHERE o.user_id = v_user.id
                          AND o.resource_id = res.id
                          AND o.effect = 'grant'))
       AND NOT EXISTS (SELECT 1 FROM attendance.user_permission_overrides o
                        WHERE o.user_id = v_user.id
                          AND o.resource_id = res.id
                          AND o.effect = 'deny');

    WITH visible AS (
        SELECT m.*, res.key AS resource_key
          FROM attendance.menu_items m
          LEFT JOIN attendance.resources res ON res.id = m.resource_id
         WHERE m.is_active
           AND p_platform = ANY(m.platforms)
           -- A row with no resource_id is a container ("User Management"). It
           -- carries no permission of its own and survives only if something
           -- under it did — see the final WHERE.
           AND (m.resource_id IS NULL OR res.key = ANY(v_perms))
    ),
    children AS (
        SELECT parent_id,
               jsonb_agg(jsonb_build_object(
                   'id', id, 'label', label, 'icon', icon,
                   'route', route, 'permission', resource_key)
                   ORDER BY sort_order) AS items
          FROM visible
         WHERE parent_id IS NOT NULL
         GROUP BY parent_id
    )
    SELECT coalesce(jsonb_agg(jsonb_build_object(
               'id', v.id, 'label', v.label, 'icon', v.icon, 'route', v.route,
               'permission', v.resource_key,
               'children', coalesce(c.items, '[]'::jsonb))
               ORDER BY v.sort_order), '[]'::jsonb)
      INTO v_menu
      FROM visible v
      LEFT JOIN children c ON c.parent_id = v.id
     WHERE v.parent_id IS NULL
       -- An empty dropdown is worse than no dropdown: it tells the user there
       -- is something there and then refuses to open.
       AND (v.resource_id IS NOT NULL OR c.items IS NOT NULL);

    RETURN jsonb_build_object(
        'status',  'success',
        'message', 'Access profile',
        'data', jsonb_build_object(
            'person_id',   v_user.person_id,
            'username',    v_user.username,
            'role',        v_user.role_key,
            'role_name',   v_user.role_name,
            'platform',    p_platform,
            'permissions', to_jsonb(v_perms),
            'menu',        v_menu,
            -- Cheap change-detection for the client, and the cheapest possible
            -- "your access changed" signal. Covers both halves of the payload,
            -- so a menu edit invalidates it as surely as a role change does.
            'version',     md5(v_perms::text || v_menu::text)));
END;
$function$;

COMMENT ON FUNCTION attendance.access_profile(bigint, text) IS
    'One person''s permissions + platform-filtered menu for POST /ext-api/me/access. Rendering hints only — attendance.ext_api_can_call() is the gate.';

-- ---------------------------------------------------------------------
-- 8 · Seed one rule per endpoint — ALL IN AUDIT MODE
--
-- `enforce = false` on every row: applying this file refuses nothing. The
-- mapping below is the proposal from docs/access_control.md §5 and is meant to
-- be argued with — confirm each line with whoever owns the process, then flip
-- them one at a time, logs first (docs §8).
--
-- NOT `ON CONFLICT`: a row that already exists has been reviewed, and possibly
-- enforced, by somebody. Re-running this file must never silently reset that.
--
-- One row is not a path at all — `save_card_info#force_reassign`. It is a
-- PERMISSION POINT: a decision inside a request that the path cannot express,
-- asked about by the handler rather than by the middleware, and enforceable on
-- its own dial. Keep the string identical to `REASSIGN_POINT` in
-- src/routes/nfc_card.rs; a mismatch reads as `no_rule`, which fails closed.
-- ---------------------------------------------------------------------

INSERT INTO attendance.ext_api_endpoint_permissions (endpoint, resource_key, enforce, note)
SELECT v.endpoint, v.resource_key, false, v.note
  FROM (VALUES
    ('/ext-api/wow-attendance/verify',              'face.verify',
        'Check-in. Readers and staff. Flip LAST: a mistake here stops people getting through doors.'),
    ('/ext-api/wow-attendance/enroll',              'face.enroll',
        'Face registration — enrolment desk.'),
    ('/ext-api/wow-attendance/check',               'face.enroll',
        'Is this person enrolled? Same audience as enroll.'),
    ('/ext-api/wow-attendance/enrolled',            'face.enroll',
        'Enrolled list — enrolment desk / admin.'),
    ('/ext-api/wow-attendance/reports/by-date',     'attendance.report.view',
        'Existing ERP permission, already granted to admin/management/faculty.'),
    ('/ext-api/wow-attendance/reports/by-person',   'attendance.report.view',
        'Existing ERP permission, already granted to admin/management/faculty.'),
    ('/ext-api/wow-attendance/ssl_image_verfiy',    'face.verify',
        'Image-only verification, no DB write. Same audience as verify.'),
    ('/ext-api/wow-attendance/mapping-save',        'attendance.settings',
        'Moves an office geo-fence. Admin only — today ANY valid token can do this.'),
    ('/ext-api/wow-attendance/logs/login',          'admin.logs.view',
        'Step logs: usernames, client IPs, DU user objects. PII — admin only. Flip FIRST.'),
    ('/ext-api/wow-attendance/logs/attendance',     'admin.logs.view',
        'Step logs: tokens, IPs, employee ids. PII — admin only. Flip FIRST.'),
    ('/ext-api/nfc-card/get_card_info',             'nfc.card.read',
        'Turnstile tap lookup. Device/service account — see docs §10. Flip LAST.'),
    ('/ext-api/nfc-card/checking_card_reg_status',  'nfc.card.status',
        'Desk check: does this student already hold a card?'),
    ('/ext-api/nfc-card/save_card_info',            'nfc.card.register',
        'Card desk. force_reassign needs nfc.card.reassign as well — checked in the handler, not here.'),
    ('/ext-api/nfc-card/save_card_info#force_reassign', 'nfc.card.reassign',
        'NOT A PATH — a permission point inside save_card_info, checked by the handler (REASSIGN_POINT in src/routes/nfc_card.rs). Taking a card off another student is grantable separately from registering one.'),
    ('/ext-api/me/access',                          NULL,
        'Deliberately open to any authenticated caller: it returns only the callers own access, and the clients need it to render anything at all.')
  ) AS v(endpoint, resource_key, note)
 WHERE NOT EXISTS (
    SELECT 1 FROM attendance.ext_api_endpoint_permissions p
     WHERE p.endpoint = v.endpoint
 );

-- ---------------------------------------------------------------------
-- 9 · Allow-list row for the access endpoint
--
-- `ExtAuthMiddleware` matches the full path against `ext_api_allowed_ips`
-- BEFORE any handler runs, so `/ext-api/me/access` would be a 403 without a
-- row — including for the desktop SPA, which cannot render a menu without it.
--
-- Open to every IP, like the NFC paths: the clients are browsers and phones on
-- networks nobody can enumerate, and the endpoint returns only the caller's
-- own access. The app credentials and the bearer token remain the gate.
--
-- Inert until the handler ships: the path 404s today, and a 404 needs no row.
-- ---------------------------------------------------------------------

INSERT INTO attendance.ext_api_allowed_ips (endpoint, ip_address)
SELECT '/ext-api/me/access', '{*}'::text[]
 WHERE NOT EXISTS (
    SELECT 1 FROM attendance.ext_api_allowed_ips a
     WHERE a.endpoint = '/ext-api/me/access'
 );

-- ---------------------------------------------------------------------
-- 10 · Afterwards
--
-- WHAT TO CHECK
--   -- Nothing is enforcing yet. 0 until you decide otherwise (docs §8).
--   SELECT count(*) FROM attendance.ext_api_endpoint_permissions WHERE enforce;
--
--   -- Did the copy land? Both sides should match, today.
--   SELECT 'roles' t, (SELECT count(*) FROM attendance.roles) mine,
--                     (SELECT count(*) FROM ictcell.roles) erp
--   UNION ALL SELECT 'resources', (SELECT count(*) FROM attendance.resources),
--                                 (SELECT count(*) FROM ictcell.resources)
--   UNION ALL SELECT 'app_users', (SELECT count(*) FROM attendance.app_users),
--                                 (SELECT count(*) FROM ictcell.app_users)
--   UNION ALL SELECT 'menu_items', (SELECT count(*) FROM attendance.menu_items),
--                                  (SELECT count(*) FROM ictcell.menu_items);
--   -- (resources will differ by this service's six keys, if ictcell never
--   --  received them.)
--
--   -- Would anyone get in? role_id is NULL on every copied row, so the honest
--   -- answer today is no — docs §7.4 has the backfill.
--   SELECT p.endpoint,
--          attendance.ext_api_can_call(2020111007, p.endpoint) ->> 'reason' AS reason
--     FROM attendance.ext_api_endpoint_permissions p ORDER BY 1;
--
-- NOBODY IS AN ADMIN UNTIL SOMEBODY IS
--   Every copied account arrived with `role_id = NULL` — the ERP never used
--   that column (docs/access_control.md §7.4). Until it is filled in, the
--   admin menus are invisible to everyone and every gated endpoint denies
--   everyone, however complete the grants above are.
--
--   Assign the accounts DU already calls admins:
--
--   UPDATE attendance.app_users
--      SET role_id = (SELECT id FROM attendance.roles WHERE key = 'admin')
--    WHERE lower(du_base_role) = 'admin' AND role_id IS NULL;
--
--   ...and check who that was, because `du_base_role` is free text and the
--   spellings are inconsistent ('Officer', 'faculty', 'ExamControllerUser'):
--
--   SELECT person_id, username, du_base_role, role_id FROM attendance.app_users
--    ORDER BY role_id NULLS LAST, person_id;
--
--   To undo one:  UPDATE attendance.app_users SET role_id = NULL WHERE person_id = …;
--
-- RE-SYNC FROM THE ERP (option (b) in the header)
--   Roles and accounts only — NOT the endpoint rules or this service's own
--   keys, which `ictcell` knows nothing about. Adds what is new; never
--   overwrites a local edit, so a role assigned here survives.
--
--   INSERT INTO attendance.roles (id, key, name, is_system, created_at)
--   SELECT id, key, name, is_system, created_at FROM ictcell.roles
--   ON CONFLICT DO NOTHING;
--   INSERT INTO attendance.app_users (id, person_id, username, du_base_role, role_id, status, last_login_at, created_at)
--   SELECT id, person_id, username, du_base_role, role_id, status, last_login_at, created_at
--     FROM ictcell.app_users ON CONFLICT DO NOTHING;
--   SELECT setval(pg_get_serial_sequence('attendance.app_users','id'),
--                 COALESCE((SELECT max(id) FROM attendance.app_users),1), true);
--
--   To let the ERP's edits WIN instead (a full mirror), add
--   `ON CONFLICT (id) DO UPDATE SET ...` — and accept that it erases whatever
--   was set here. Pick one direction and write it down; two-way sync between
--   two schemas nobody owns jointly is how this ends up inconsistent.
--
-- THE `ictcell` RESIDUE
--   An earlier version of this migration wrote to `ictcell`: six resource keys
--   and a `platforms` column on `menu_items`. Both are now redundant here, and
--   harmless — the ERP shows only what its menus reference, and the column has
--   a default. Remove them only once nothing reads them:
--
--   -- ALTER TABLE ictcell.menu_items DROP COLUMN IF EXISTS platforms;
--   -- DELETE FROM ictcell.resources WHERE key LIKE 'nfc.%' OR key LIKE 'face.%';
-- ---------------------------------------------------------------------
